---
# ------------------------------------------------------------------------------------------------------------------------
sap_sid: 
sap_instancenum: 
sap_hostname: 

# ------------------------------------------------------------------------------------------------------------------------
# -----------------------------URLs for HANA DB Installation--------------------------------------------------------------
# Default URLs
# url_sapcar:
# url_hdbserver:
# url_hcmt: https://softwaredownloads.sap.com/file/0020000000392012021
# using own accessible storage account:
url_sapcar: https://terraform2021.blob.core.windows.net/sapbits/archives/SAPCAR_1010-70006178.EXE
url_hdbserver: https://terraform2021.blob.core.windows.net/sapbits/archives/IMDB_SERVER20_055_0-80002031.SAR
url_hcmt: https://terraform2021.blob.core.windows.net/sapbits/archives/HCMT_055_0-80003261.SAR 

url_cockpit:
url_di_core:
url_portal_services:
url_shine_xsa:
url_xs_services:
url_xsa_runtime:
url_xsa_hrtt:
url_xsa_webide:
url_xsa_mta:

url_retries_delay: 10
url_timeout: 30
url_retries_cnt: 20

install_cockpit: false
install_shine: false
install_xsa: false

email_shine: "shinedemo@microsoft.com"

# ------------------------------------------------------------------------------------------------------------------------
# -----------------------------URL for the Azure HANA Backint Integration Script------------------------------------------
# Default:
# url_msawb_plugin: https://aka.ms/ScriptForPermsOnHANA?clcid=0x0409
# using own accessible storage account:
url_msawb_plugin: https://terraform2021.blob.core.windows.net/sapdeployments/msawb-plugin-config-com-sap-hana.sh

# ------------------------------------------------------------------------------------------------------------------------